# Generated by Django 4.2.27 on 2026-01-11 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser_created_at_alter_article_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='dislikes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articlereaction',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='main.article'),
        ),
    ]
