# Generated by Django 4.2.27 on 2026-01-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_article_dislikes_count_article_likes_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='follower',
            new_name='follower_count',
        ),
        migrations.AddField(
            model_name='customuser',
            name='following_count',
            field=models.IntegerField(default=0),
        ),
    ]
