# Generated by Django 4.2.27 on 2026-01-13 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_article_views_count_articleview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewed_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
